### ISSUE TITLE
Ternary expression is not working (even if I use EnumerableExtensions)

### ISSUE THREAD

**Issue by podkolzzzin** [Bardin08/Ctoss#13]
![зображення](https://github.com/user-attachments/assets/82d1e839-84f9-481a-8dbb-b2f07e82d140)

**Comment by podkolzzzin** [comment]
The same with MethodCall
![зображення](https://github.com/user-attachments/assets/13a11c96-210e-4e26-962d-0ef957c2ed00)

**Comment by Bardin08** [comment]
Fixed in #15
